version: '3.4'

x-args:
  &default-args
  dev_path: ./local_dev
  github_token: ${GITHUB_TOKEN}
  SSH_PRIV_KEY: ${SSH_PRIV_KEY}

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: ${LOG_MAX_SIZE}
    max-file: ${LOG_MAX_FILE}

services:
  abtesting-service:
    build:
      context: ../
      dockerfile: ./local_dev/django-service.dockerfile
      args:
        << : *default-args
        service_path: ./abtesting-service
    command: python manage.py runserver 0.0.0.0:8002
    entrypoint: /usr/src/entry.sh
    environment:
      - ABTESTING_CFG_FILE=app/${CONFIG_FILE}
    depends_on:
      - db
    logging: *default-logging
    ports: ['8002:8002']
    volumes:
      - ../abtesting-service:/usr/src/app
      # - ../woodhouse/:/usr/src/libraries/woodhouse

  chrono:
    build:
      context: ../
      dockerfile: ./local_dev/django-service.dockerfile
      args:
        << : *default-args
        service_path: ./chronotrigger
    command: python manage.py runserver 0.0.0.0:8001
    entrypoint: /usr/src/entry.sh
    environment:
      - CHRONO_CFG_FILE=app/${CONFIG_FILE}
    depends_on:
      - db
      - memcached
      - mongo
    logging: *default-logging
    ports: ['8001:8001']
    volumes:
      - ../chronotrigger:/usr/src/app
      # - ../woodhouse/:/usr/src/libraries/woodhouse

  chrono-celery:
    build:
      context: ../
      dockerfile: ./local_dev/celery-service.dockerfile
      args:
        << : *default-args
        service_path: ./chronotrigger
    command: watchmedo auto-restart --directory . -p '*.py' --recursive -- celery worker --beat --scheduler django --app celery_app -l info
    entrypoint: /usr/src/entry.sh
    environment:
      - CHRONO_CFG_FILE=app/${CONFIG_FILE}
    depends_on:
      - db
      - memcached
      - mongo
      - rabbitmq
    logging: *default-logging
    volumes:
      - ../chronotrigger:/usr/src/app
      # - ../woodhouse/:/usr/src/libraries/woodhouse

  lego:
    build:
      context: ../
      dockerfile: ./local_dev/lego.dockerfile
      args:
        << : *default-args
        SERVICE_PATH: ./lego
    command: python ./lego/manage.py runserver 0.0.0.0:7001 --settings=lego.settings_local
    # entrypoint: /app/entry.sh
    environment:
      - SETTINGS_FILE=./.env.container.cfg
    depends_on:
      - mariadb
      - memcached
      - rabbitmq
      - mongo
    logging: *default-logging
    ports: ['7001:7001']
    volumes:
      - ../lego:/app
      # - ../woodhouse/:/usr/src/libraries/woodhouse
      # - ../whiskey/:/usr/src/libraries/whiskey
      # - ../ordergroove_nucleus/:/usr/src/libraries/ordergroove_nucleus

  memento:
    build:
      context: ../
      dockerfile: ./local_dev/celery-service.dockerfile
      args:
        << : *default-args
        service_path: ./memento
    command: watchmedo auto-restart --directory ./memento --directory ../libraries/ -p '*.py' --recursive -- celery worker --app memento.celery_app -l info -n og@%h
    entrypoint: /usr/src/entry.sh
    environment:
      - PYTHONPATH=/usr/src/app/memento
      - MEMENTO_CFG_FILE=${CONFIG_FILE}
    depends_on:
      - memcached
      - mongo
      - rabbitmq
    logging: *default-logging
    volumes:
      - ../memento:/usr/src/app
      # - ../woodhouse/:/usr/src/libraries/woodhouse

  moonshine-api:
    build:
      context: ../
      dockerfile: ./local_dev/django-service.dockerfile
      args:
        << : *default-args
        service_path: ./moonshine-api
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /usr/src/entry.sh
    environment:
     - MOONSHINE_CFG_FILE=app/${CONFIG_FILE}
    depends_on:
      - db
      - memcached
      - rabbitmq
    logging: *default-logging
    ports: ['8000:8000']
    volumes:
      - ../moonshine-api:/usr/src/app
      # - ../moonshine-core/:/usr/src/libraries/moonshine-core
      # - ../woodhouse/:/usr/src/libraries/woodhouse

  moonshine-celery:
    build:
      context: ../
      dockerfile: ./local_dev/celery-service.dockerfile
      args:
        << : *default-args
        service_path: ./moonshine-celery
    command: watchmedo auto-restart --directory . -p '*.py' --recursive -- celery worker --app celery_app --loglevel=info
    entrypoint: /usr/src/entry.sh
    environment:
      - MOONSHINE_CFG_FILE=app/${CONFIG_FILE}
    depends_on:
      - db
      - memcached
      - rabbitmq
    logging: *default-logging
    volumes:
      - ../moonshine-celery:/usr/src/app
      # - ../moonshine-core/:/usr/src/libraries/abtesting
      # - ../moonshine-core/:/usr/src/libraries/moonshine-core
      # - ../woodhouse/:/usr/src/libraries/woodhouse

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: ['3307:3306']
    environment:
      # MYSQL_USER:
      # MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: example
    logging: *default-logging
    volumes:
      - db_data:/data/db

  mariadb:
    image: mariadb
    restart: always
    ports: ['3308:3306']
    environment:
      MYSQL_ROOT_PASSWORD: ogpassw
    logging: *default-logging
    volumes:
      - mariadb_data:/data/db

  memcached:
    image: memcached
    ports: ['11212:11211']

  mongo:
    image: mongo
    restart: always
    ports: ['27018:27017']
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    logging: *default-logging
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
      RABBITMQ_DEFAULT_VHOST: '/'
    logging: *default-logging
    ports:
      - '15673:15672'
      - '5673:5672'

  redis:
    image: redis
    ports: ['6380:6379']
    logging: *default-logging

volumes:
  db_data:
  mariadb_data:
  mongo_data:
