version: '3'

services:

  chrono:
    build:
      context: ../
      dockerfile: ./local_dev/django-service.dockerfile
      args:
        dev_path: ./local_dev
        github_token: ${GITHUB_TOKEN}
        service_path: ./chronotrigger
    command: python manage.py runserver 0.0.0.0:8001
    entrypoint: /usr/src/entry.sh
    depends_on:
      - db
      - memcached
      - mongo
    logging:
      driver: 'json-file'
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}
    ports: ['8001:8001']
    volumes:
      - ../chronotrigger:/usr/src/app
      # - ../woodhouse/:/usr/src/libraries/woodhouse

  chrono-celery:
    build:
      context: ../
      dockerfile: ./local_dev/celery-service.dockerfile
      args:
        dev_path: ./local_dev
        github_token: ${GITHUB_TOKEN}
        service_path: ./chronotrigger
    command: celery worker --beat --scheduler django --app celery_app -l info
    entrypoint: /usr/src/entry.sh
    depends_on:
      - db
      - memcached
      - mongo
      - rabbitmq
    logging:
      driver: 'json-file'
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}
    volumes:
      - ../chronotrigger:/usr/src/app
      # - ../woodhouse/:/usr/src/libraries/woodhouse

  moonshine-api:
    build:
      context: ../
      dockerfile: ./local_dev/django-service.dockerfile
      args:
        dev_path: ./local_dev
        github_token: ${GITHUB_TOKEN}
        service_path: ./moonshine-api
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /usr/src/entry.sh
    depends_on:
      - db
      - memcached
    logging:
      driver: 'json-file'
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}
    ports: ['8000:8000']
    volumes:
      - ../moonshine-api:/usr/src/app
      # - ../woodhouse/:/usr/src/libraries/woodhouse
      - ../moonshine-core/:/usr/src/libraries/moonshine-core

  moonshine-celery:
    build:
      context: ../
      dockerfile: ./local_dev/celery-service.dockerfile
      args:
        dev_path: ./local_dev
        github_token: ${GITHUB_TOKEN}
        service_path: ./moonshine
    command: celery worker --app celery_app --loglevel=info
    entrypoint: /usr/src/entry.sh
    depends_on:
      - rabbitmq
    logging:
      driver: 'json-file'
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}
    volumes:
      - ../moonshine:/usr/src/app
      # - ../woodhouse/:/usr/src/libraries/woodhouse
      - ../moonshine-core/:/usr/src/libraries/moonshine-core

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: ['3307:3306']
    environment:
      # MYSQL_USER:
      # MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/data/db

  memcached:
    image: memcached
    ports: ['11212:11211']

  mongo:
    image: mongo
    restart: always
    ports: ['27018:27017']
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15673:15672'
      - '5673:5672'

  redis:
    image: redis
    ports: ['6380:6379']

volumes:
  db_data:
  mongo_data:
